### ISSUE TITLE
Regression due to usage of is_inside function

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [minetest-mirrors/mobs_redo#1]
A function is_inside was introduced that can detect with which nodes the collision box of a mob overlaps:
https://github.com/minetest-mirrors/mobs_redo/commit/ed74f3c4c4d3f4c7e17127fa26ac4f0adbd2900d

This function does what (I guess) it is supposed to do - so there's no bug in the function.
However, using this function comes with some consequences:

1. The check requires more computational resources
2. A mob can now be "in" multiple nodes at the same location and time

This function is used in 2 locations both in [do_env_damage](https://github.com/minetest-mirrors/mobs_redo/blob/dce2abfcfe4ddc18d2d8d683b176ddb74c6dd209/api.lua#L994-L1115):
[api.lua line 1025](https://github.com/minetest-mirrors/mobs_redo/blob/dce2abfcfe4ddc18d2d8d683b176ddb74c6dd209/api.lua#L1025) and [1035](https://github.com/minetest-mirrors/mobs_redo/blob/dce2abfcfe4ddc18d2d8d683b176ddb74c6dd209/api.lua#L1035)
That function uses an elseif logic - which is not compatible to 2) of the consequences I mentioned.

As a result mobs that are e.g. damaged by water nodes can't heal due to being in other nodes - because the water check comes first.
Similarly e.g. a lava flan that is "in" a lava node **and** a damaging node will only heal ignoring the damage because the lava check comes first.

From what I can tell this function has only downsides compared to the nodef checks in the places it is used I found and mentioned so I would like to propose to not use it in those places at least.

**Comment by Niklp09** [comment]
This repo is just a mirror, please report issues upstream at https://codeberg.org/tenplus1/mobs_redo/issues.

**Comment by FeXoR-o-Illuria** [comment]
Thank you @Niklp09 , done: https://codeberg.org/tenplus1/mobs_redo/issues/30

I'll try to close it here ;)
